# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

sensor:
  - platform: integration
    source: sensor.mill_heatergen3panel_current_power
    name: mill_office_heater_total_active_power_raw
    method: trapezoidal
  - platform: integration
    source: sensor.mill_heatergen3panel_current_power_2
    name: mill_attic_heater_total_active_power_raw
    method: trapezoidal
  - platform: time_date
    display_options:
      - 'time'
      - 'date'
      - 'date_time'

template:
  - sensor:
      - name: mill_office_heater_total_active_power
        unit_of_measurement: "kWh"
        device_class: energy
        state_class: total_increasing
        state: "{{ states('sensor.mill_office_heater_total_active_power_raw') }}"
        attributes:
          friendly_name: "Mill office heater total active power"

      - name: mill_attic_heater_total_active_power
        unit_of_measurement: "kWh"
        device_class: energy
        state_class: total_increasing
        state: "{{ states('sensor.mill_attic_heater_total_active_power_raw') }}"
        attributes:
          friendly_name: "Mill attic heater total active power"

      - name: current_energy_price_eur
        unit_of_measurement: "EUR/kWh"
        device_class: monetary
        state_class: measurement
        state: >
          {% set transmission_fee_day = 0.0617 %}
          {% set transmission_fee_night = 0.0357 %}
          {% set renewable_fee = 0.0084 %}
          {% set excise_fee = 0.0021 %}
          {% set vat_multiplier = 1.24 %}
          {% set now_obj = now() %}

          {% set m = now_obj.month %}
          {% set d = now_obj.day %}
          {% set y = now_obj.year %}

          {% set is_fixed_holiday = (
            (m == 1 and d == 1) or (m == 2 and d == 24) or (m == 5 and d == 1) or
            (m == 6 and d == 23) or (m == 6 and d == 24) or (m == 8 and d == 20) or
            (m == 12 and d == 24) or (m == 12 and d == 25) or (m == 12 and d == 26)
          ) %}

          {% set a = y % 19 %}
          {% set b = y // 100 %}
          {% set c = y % 100 %}
          {% set d1 = b // 4 %}
          {% set e = b % 4 %}
          {% set f = (b + 8) // 25 %}
          {% set g = (b - f + 1) // 3 %}
          {% set h = (19 * a + b - d1 - g + 15) % 30 %}
          {% set i = c // 4 %}
          {% set k = c % 4 %}
          {% set l = (32 + 2 * e + 2 * i - h - k) % 7 %}
          {% set m1 = (a + 11 * h + 22 * l) // 451 %}
          {% set easter_month = (h + l - 7 * m1 + 114) // 31 %}
          {% set easter_day = ((h + l - 7 * m1 + 114) % 31) + 1 %}
          {% set easter_date = strptime(y ~ '-' ~ easter_month ~ '-' ~ easter_day, '%Y-%m-%d').date() %}
          {% set good_friday_date = easter_date - timedelta(days=2) %}
          {% set pentecost_date = easter_date + timedelta(days=49) %}

          {% set is_moving_holiday = (
            (m == good_friday_date.month and d == good_friday_date.day) or
            (m == easter_date.month and d == easter_date.day) or
            (m == pentecost_date.month and d == pentecost_date.day)
          ) %}

          {# Final check for Night Rate Applicability #}
          {% set is_holiday = is_fixed_holiday or is_moving_holiday %}
          {% set is_weekend = now_obj.weekday() >= 5 %} {# 5=Saturday, 6=Sunday #}
          {% set is_night_hours = now_obj.hour < 7 or now_obj.hour >= 22 %}

          {% if is_holiday or is_weekend or is_night_hours %}
            {% set current_transmission_fee = transmission_fee_night %}
          {% else %}
            {% set current_transmission_fee = transmission_fee_day %}
          {% endif %}

          {% set price_without_fees_and_vat = states('sensor.nord_pool_ee_current_price') | float %}
          {% set total_extra_costs = current_transmission_fee + renewable_fee + excise_fee %}
          {% set final_price = (price_without_fees_and_vat + total_extra_costs) * vat_multiplier %}
          {{ final_price | round(5) }}
        attributes:
          friendly_name: "Current energy price EUR/kWh"

      - name: hourly_total_price
        unit_of_measurement: "€"
        device_class: monetary
        state_class: measurement
        state: >
          {% set energy_consumption = states('sensor.hourly_energy') | float %}
          {% set energy_price = states('sensor.current_energy_price_eur') | float %}
          {{ (energy_consumption * energy_price) }}
        attributes:
          friendly_name: "Hourly Total Price"
  - sensor:
      - name: time_of_day
        state: >
          {% set hour = now().hour %}
          {% if 5 <= hour < 12 %}
            morning
          {% elif 12 <= hour < 18 %}
            day
          {% elif 18 <= hour < 22 %}
            evening
          {% else %}
            night
          {% endif %}
        attributes:
          friendly_name: "Time of day"

utility_meter:
  hourly_energy:
    source: sensor.shellypro3em_2cbcbba6f604_total_active_energy
    cycle: hourly

  hourly_energy_cost:
    source: sensor.hourly_total_price
    cycle: hourly

  daily_energy:
    source: sensor.shellypro3em_2cbcbba6f604_total_active_energy
    cycle: daily

  daily_energy_cost:
    source: sensor.hourly_total_price
    cycle: daily

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.60.64

input_number:
  min_temp:
    name: Temperatuur min
    min: 10
    max: 14.5
    step: 0.5
    unit_of_measurement: "°C"

  max_temp:
    name: Temperatuur max
    min: 15
    max: 26
    step: 0.5
    unit_of_measurement: "°C"

  min_price:
    name: Elektrihind min
    min: 6
    max: 19.5
    step: 0.5
    unit_of_measurement: "senti/kWh"

  max_price:
    name: Elektrihind max
    min: 20
    max: 50
    step: 0.5
    unit_of_measurement: "senti/kWh"

  # Room target temperatures
  living_room_temp:
    name: Elutoa temperatuur
    min: 16
    max: 26
    step: 0.5
    unit_of_measurement: "°C"
    initial: 21

  office_temp:
    name: Kontorin temperatuur
    min: 16
    max: 26
    step: 0.5
    unit_of_measurement: "°C"
    initial: 20

  attic_temp:
    name: Pööningu temperatuur
    min: 16
    max: 26
    step: 0.5
    unit_of_measurement: "°C"
    initial: 19

input_boolean:
  away_mode:
    name: Äraoleku režiim
