alias: Dynamic Climate Control
description: Adjust climate based on electricity price.
triggers:
  - entity_id:
      - sensor.current_energy_price_eur
      - input_number.min_price
      - input_number.max_price
      - input_number.min_temp
      - input_number.max_temp
      - input_boolean.away_mode
    trigger: state
conditions: []
actions:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ away_mode }}"
        sequence:
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ current_price < min_price }}"
                sequence:
                  - target:
                      device_id:
                        - 29113dc51f50d91328a55261fd8de2a2
                        - 15cbc96ee1ff142c5b0274eaf7f12c4e
                        - 03d66744855d1695848cff33a60a43d5
                    data:
                      temperature: "{{ max_temp }}"
                    action: climate.set_temperature
              - conditions:
                  - condition: template
                    value_template: "{{ current_price >= min_price }}"
                sequence:
                  - target:
                      device_id:
                        - 29113dc51f50d91328a55261fd8de2a2
                        - 15cbc96ee1ff142c5b0274eaf7f12c4e
                    data:
                      temperature: "{{ min_temp }}"
                    action: climate.set_temperature
                  - target:
                      device_id:
                        - 03d66744855d1695848cff33a60a43d5
                    data:
                      temperature: "{{ mitsubishi_min_temp }}"
                    action: climate.set_temperature
      - conditions:
          - condition: template
            value_template: "{{ not away_mode }}"
        sequence:
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ current_price < min_price }}"
                sequence:
                  - target:
                      device_id:
                        - 29113dc51f50d91328a55261fd8de2a2
                        - 15cbc96ee1ff142c5b0274eaf7f12c4e
                        - 03d66744855d1695848cff33a60a43d5
                    data:
                      temperature: "{{ max_temp }}"
                    action: climate.set_temperature
              - conditions:
                  - condition: template
                    value_template: >-
                      {{ current_price >= min_price and current_price <
                      max_price }}
                sequence:
                  - target:
                      device_id:
                        - 29113dc51f50d91328a55261fd8de2a2
                        - 15cbc96ee1ff142c5b0274eaf7f12c4e
                    data:
                      temperature: |
                        {{
                          max_temp -
                          (
                            (current_price - min_price) / (max_price - min_price)
                          )
                          * (max_temp - min_temp)
                        }}
                    action: climate.set_temperature
                  - target:
                      device_id:
                        - 03d66744855d1695848cff33a60a43d5
                    data:
                      temperature: |
                        {{
                          max_temp -
                          (
                            (current_price - min_price) / (max_price - min_price)
                          )
                          * (max_temp - mitsubishi_min_temp)
                        }}
                    action: climate.set_temperature
              - conditions:
                  - condition: template
                    value_template: "{{ current_price >= max_price }}"
                sequence:
                  - target:
                      device_id:
                        - 29113dc51f50d91328a55261fd8de2a2
                        - 15cbc96ee1ff142c5b0274eaf7f12c4e
                    data:
                      temperature: "{{ min_temp }}"
                    action: climate.set_temperature
                  - target:
                      device_id:
                        - 03d66744855d1695848cff33a60a43d5
                    data:
                      temperature: "{{ mitsubishi_min_temp }}"
                    action: climate.set_temperature
mode: queued
variables:
  current_price: "{{ states('sensor.current_energy_price_eur')|float }}"
  min_price: "{{ states('input_number.min_price')|float }}"
  max_price: "{{ states('input_number.max_price')|float }}"
  min_temp: "{{ states('input_number.min_temp')|float }}"
  max_temp: "{{ states('input_number.max_temp')|float }}"
  away_mode: "{{ is_state('input_boolean.away_mode', 'on') }}"
  mitsubishi_min_temp: 18
